### PR TITLE
Ansible Collections using "message" as parameters can fail

### PR DESCRIPTION
**Pull request by stiivo**
Hi Markus,

at first, thanks for this pretty handy collection. I tried to use it with ansible 4. While playing with it, i realized that the talk method was not working.  I was facing the following error:

    Traceback (most recent call last):
      File "/home/stevg/.ansible/tmp/ansible-tmp-1623140357.3210704-1162578-18247537908204/AnsiballZ_talk.py", line 100, in <module>
        _ansiballz_main()
      File "/home/stevg/.ansible/tmp/ansible-tmp-1623140357.3210704-1162578-18247537908204/AnsiballZ_talk.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/stevg/.ansible/tmp/ansible-tmp-1623140357.3210704-1162578-18247537908204/AnsiballZ_talk.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.markuman.nextcloud.plugins.modules.talk', init_globals=dict(_module_fqn='ansible_collections.markuman.nextcloud.plugins.modules.talk', _modlib_path=modlib_path),
      File "/usr/lib64/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_markuman.nextcloud.talk_payload_l4frj0qu/ansible_markuman.nextcloud.talk_payload.zip/ansible_collections/markuman/nextcloud/plugins/modules/talk.py", line 89, in <module>
      File "/tmp/ansible_markuman.nextcloud.talk_payload_l4frj0qu/ansible_markuman.nextcloud.talk_payload.zip/ansible_collections/markuman/nextcloud/plugins/modules/talk.py", line 58, in main
      File "/tmp/ansible_markuman.nextcloud.talk_payload_l4frj0qu/ansible_markuman.nextcloud.talk_payload.zip/ansible/module_utils/basic.py", line 523, in __init__
      File "/tmp/ansible_markuman.nextcloud.talk_payload_l4frj0qu/ansible_markuman.nextcloud.talk_payload.zip/ansible/module_utils/basic.py", line 1384, in _log_invocation
      File "/tmp/ansible_markuman.nextcloud.talk_payload_l4frj0qu/ansible_markuman.nextcloud.talk_payload.zip/ansible/module_utils/basic.py", line 1341, in log
    TypeError: systemd.journal.send() got multiple values for keyword argument 'MESSAGE'

While googling for it i found 2 Issues in the ansible main repository which are referencing this error in combinations with other collections. I decided to fork your collection and simply changed the message parameter to msg. Everything is working for me now. 

Thanks again!

### CODE REVIEW

**Comment by stiivo** [comment]
Sorry the change for passwords.py should not be included in this pull request.

**Comment by markuman** [comment]
Can you add the links to the other issues  @stiivo ?  
So basically a change of the parametername itself from `message` to `msg` is sufficient? Internally it can use `message` I guess.

Are you facing also issues with the passwords lookup plugin?

**Comment by stiivo** [comment]
https://github.com/ansible/ansible/issues/39295
https://github.com/ansible/ansible/pull/60051

No issues with password lookup at all. It was just more practical for me to get the the whole JSON Object to be able to use the username value too so i can use "{{ lookupValue.username }}"

**Comment by markuman** [comment]
> [ansible/ansible#39295](https://github.com/ansible/ansible/issues/39295)
> [ansible/ansible#60051](https://github.com/ansible/ansible/pull/60051)
> 
> No issues with password lookup at all. It was just more practical for me to get the the whole JSON Object to be able to use the username value too so i can use "{{ lookupValue.username }}"

maybe we can add an option parameter `want_full_object=True` or something like that.  
Default is `False` and will return only the password.  
What do you think?

**Comment by stiivo** [comment]
Sounds good to me. 

I was thinking about if it would be reasonable to add functionality to be able to add/modify/delete passwords?
Nextcloud Passwords could act as complete Credentials Store (Vault?) for Ansible.   
We are using Nextcloud Passwords in a corporate environment (10-20 employees) and im thinking about using ansible for regular automated credential rotation (mainly web services). I think others and i could make good use of the features mentioned above.

Whats your opinion about this?

I'm anything but a python programmer (time to start, i guess ;)) but I would trust myself to implement these functions if you would agree.

**Comment by markuman** [comment]
> Sounds good to me.
> 
> I was thinking about if it would be reasonable to add functionality to be able to add/modify/delete passwords?
> Nextcloud Passwords could act as complete Credentials Store (Vault?) for Ansible.

I was also thinking about it. It must result in a `markuman,nextcoud.password` module.

> We are using Nextcloud Passwords in a corporate environment (10-20 employees)

lucky you :)

**Comment by markuman** [comment]
@stiivo fyi https://github.com/markuman/nextcloud_collection/releases/tag/4.0.0

**Comment by markuman** [comment]
@stiivo 6.0.0 includes now `details` parameter for password lookup

When `details=False`, only the password is returned.  
When `details=True`, the entire object is returned.

```yml
- name: Retrieve Password with label "Stackoverflow"
  debug:
    var: lookup('markuman.nextcloud.passwords', 'Stackoverflow' , host='nextcloud.tld', user='ansible', api_token='some-token', details=False)
```

**Comment by markuman** [comment]
@stiivo fyi: in the main branch is a first draft for `password_info` module, which shares the same codebase as `password` lookup plugin, but forces the details settings.  
`password` module comes next. hopefully with  create, update, delete and share capabilities.

**Pull request closed without merging**
